org: davidtbootle
service: youtube-downloader
provider:
  name: aws
  runtime: nodejs12.x
  stage: 
  region: us-east-2
  memorySize: 128
functions:
app: youtube-downloader-app
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true